version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      artifacts:
        patterns:
          - "actions/*-artifact"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
