name: Docs

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Generate Docs
      run: cargo doc --no-deps
    - name: Prepare docs for deployment
      run: |
        mkdir gh-pages
        echo "<meta http-equiv=\"refresh\" content=\"0; url=peng_quad\index.html\">" > target/doc/index.html
        mv target/doc/* gh-pages/
        touch gh-pages/.nojekyll
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        force_orphan: true
